services:
  nginx:
    image: nginx:alpine
    container_name: sendmail_nginx
    ports:
      - "80:80"
    volumes:
      - ../../Frontend:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
